<?php
	namespace ewgraFramework;
	
	$meta = $model->get('meta');
	echo '<?php'.PHP_EOL;
	
	$namespace = $meta->getDocumentElement()->getAttribute('namespace');
	
	if ($namespace) {
?>
	namespace <?=$namespace?>;
	
<?php 
	}
?>
	/**
	 * Generated by meta builder!
	 * Do not edit this file!
	*/
	
	ClassesAutoloader::me()->addSearchDirectory(dirname(__FILE__));
	
<?php
	foreach (
		$meta->getNodeList(
			'*/properties/*[@class=/meta/*[@generate="false" and @type="Identifier"]/@fullClassName]'
		) as $node
	) {
		$parent = $node->parentNode->parentNode;		
?>
	<?=$node->getAttribute('class')?>::da()->addLinkedCacher(<?=$parent->nodeName?>::da());
<?php
	}

	echo '?>';
?>