<?php
	$meta = $model->get('meta');
	
	$classNode = $meta->getNode($meta->getNode('className')->nodeValue);
	
	$extends = $classNode->getAttribute('extends');

	if ($extends)
		$extends = ' extends '.$extends;
	
	echo '<?php'.PHP_EOL;
?>
	/**
	 * Generated by meta builder!
	 * Do not edit this class!
<?php
	PhpView::includeFile(
		dirname(__FILE__).'/phpDocClass.php',
		$model
	);
?>
	 */
	abstract class Auto<?=$classNode->nodeName?><?=$extends.PHP_EOL?>
	{
<?php
	$properies = $meta->getNodeList('properties/*', $classNode);

	foreach ($properies as $property) {
		$class = $property->getAttribute('class');
		$classType = $property->getAttribute('classType');
		
		$phpDocVar = $class;
		
		if (!$phpDocVar)
			$phpDocVar = $property->getAttribute('type');
		
		if ($phpDocVar) {
?>
		/**
		 * @var <?=$phpDocVar.PHP_EOL?>
		 */
<?php
		}
?>
		private $<?=$property->nodeName?> = null;
		
<?php
	}
?>
		/**
		 * @return <?=$classNode->nodeName?>DA
		 */
		public static function da()
		{
			return <?=$classNode->nodeName?>DA::me();
		}
<?php
	$properties = $meta->getNodeList('properties/*', $classNode);
	
	foreach ($properties as $property) {
		$modelProperty =
			Model::create()->
			set('meta', $meta)->
			set('property', $property)->
			set('generateClassName', $classNode->nodeName);
		
		PhpView::includeFile(
			dirname(__FILE__).'/businessClassSetter.php',
			$modelProperty
		);

		PhpView::includeFile(
			dirname(__FILE__).'/businessClassGetter.php',
			$modelProperty
		);
	}
?>
	}
<?php
	echo '?>';
?>