<?php
	$meta = $model->get('meta');
	
	$classNode = $meta->getNode($meta->getNode('className')->nodeValue);
	
	echo '<?php'.PHP_EOL;
?>
	/**
	 * Generated by meta builder, you can edit this class
<?php
	PhpView::includeFile(
		dirname(__FILE__).'/phpDocClass.php',
		$model
	);
?>
	 */
	final class <?=$classNode->nodeName?>DA extends Auto<?=$classNode->nodeName?>DA
	{
		/**
		 * @return <?=$classNode->nodeName?>DA
		 */
		public static function me()
		{
			return parent::getInstance(__CLASS__);
		}
	}
<?php
	echo '?>';
?>